"""Add observations table

Revision ID: 1b804f80154f
Revises: 
Create Date: 2026-01-23 00:17:38.966530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b804f80154f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('school_year_id', sa.Integer(), nullable=False))
    op.alter_column('observations', 'score',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='score::integer')
    op.drop_constraint(op.f('observations_created_by_id_fkey'), 'observations', type_='foreignkey')
    op.create_foreign_key(None, 'observations', 'school_years', ['school_year_id'], ['id'])
    op.drop_column('observations', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.create_foreign_key(op.f('observations_created_by_id_fkey'), 'observations', 'users', ['created_by_id'], ['id'])
    op.alter_column('observations', 'score',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('observations', 'school_year_id')
    # ### end Alembic commands ###
